# Generated by Django 5.2.12 on 2026-04-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("participante", "Participante")],
                default="participante",
                max_length=20,
            ),
        ),
    ]