# Generated by Django 5.2.12 on 2026-04-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_update_user_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_mode_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="email_app_password",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
