# Generated by Django 5.2.12 on 2026-04-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("instructors", "0004_instructor_signature_image"),
        (
            "participants",
            "0002_rename_participant_is_acti_idx_participant_is_acti_525b89_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="enrollment",
            name="unique_participant_event",
        ),
        migrations.RemoveConstraint(
            model_name="eventinstructor",
            name="unique_event_instructor",
        ),
        migrations.RenameIndex(
            model_name="enrollment",
            new_name="events_enro_partici_1aa7fd_idx",
            old_name="enrollment_participant_event_idx",
        ),
        migrations.RenameIndex(
            model_name="enrollment",
            new_name="events_enro_attenda_b9b9db_idx",
            old_name="enrollment_attendance_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_even_status_5709b6_idx",
            old_name="event_status_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_even_event_d_2c2da5_idx",
            old_name="event_date_idx",
        ),
        migrations.RenameIndex(
            model_name="eventinvitation",
            new_name="events_even_token_badcdb_idx",
            old_name="invitation_token_idx",
        ),
        migrations.RenameIndex(
            model_name="eventinvitation",
            new_name="events_even_status_4a554f_idx",
            old_name="invitation_status_idx",
        ),
        migrations.RenameIndex(
            model_name="eventinvitation",
            new_name="events_even_email_014078_idx",
            old_name="invitation_email_event_idx",
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("participant", "event")},
        ),
        migrations.AlterUniqueTogether(
            name="eventinstructor",
            unique_together={("event", "instructor")},
        ),
    ]
