# Generated by Django 5.2.12 on 2026-04-17 02:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_add_created_by_fields"),
        ("students", "0003_student_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="certificate_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="certificate_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="certificate_sent_method",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="invitation_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="auto_send_certificates",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="EventInvitation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviada"),
                            ("accepted", "Aceptada"),
                            ("rejected", "Rechazada"),
                            ("expired", "Expirada"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="events.event",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_invitations",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        # Skip adding invitation_id column as it already exists
        migrations.AddConstraint(
            model_name="eventinvitation",
            constraint=models.UniqueConstraint(
                fields=["email", "event"], name="unique_email_event"
            ),
        ),
        migrations.AddIndex(
            model_name="eventinvitation",
            index=models.Index(fields=["token"], name="events_even_token_badcdb_idx"),
        ),
        migrations.AddIndex(
            model_name="eventinvitation",
            index=models.Index(fields=["status"], name="events_even_status_4a554f_idx"),
        ),
        migrations.AddIndex(
            model_name="eventinvitation",
            index=models.Index(
                fields=["email", "event"], name="events_even_email_014078_idx"
            ),
        ),
    ]
