# Generated by Django 5.2.12 on 2026-06-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_historicalevent_event_deleted_at_event_deleted_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="font_color",
            field=models.CharField(default="#1e3a8a", max_length=20),
        ),
        migrations.AddField(
            model_name="historicalevent",
            name="font_color",
            field=models.CharField(default="#1e3a8a", max_length=20),
        ),
    ]
