# Generated by Django 5.2.12 on 2026-04-21 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificados", "0006_update_coord_types"),
        ("events", "0005_remove_eventinvitation_unique_email_event_and_more"),
        ("instructors", "0003_instructor_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="events.eventinvitation",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="instructors.instructor",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="invitation_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="event",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="max_capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="name_font_size",
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name="event",
            name="name_x",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="event",
            name="name_y",
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name="event",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="certificados.template",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="template_image",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="eventinstructor",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_instructors",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="eventinstructor",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_instructor_roles",
                to="instructors.instructor",
            ),
        ),
    ]
