# Generated by Django 5.2.12 on 2026-03-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
