sonar.projectKey=hectorpq_certybackend
sonar.organization=hectorpq11
sonar.projectName=CertyPro - Backend

sonar.sources=.
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/*.pyc,**/admin.py,**/apps.py,config/wsgi.py,config/asgi.py,manage.py,services/whatsapp_service.py

sonar.coverage.exclusions=**/admin.py,**/apps.py,config/wsgi.py,config/asgi.py,manage.py,services/whatsapp_service.py,certificados/views.py,core/views.py,deliveries/views.py,emails/views.py,events/views.py,instructors/views.py,procesos/views.py,students/views.py,users/views.py

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

# Suppress false positives in test files
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*tests.py
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S125
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*tests.py