sonar.organization=hectorpq11
sonar.projectKey=hectorpq_certybackend
sonar.projectName=CertyPro - Backend
sonar.language=py
sonar.python.version=3.12
sonar.sources=api, certificados, config, core, deliveries, emails, events, instructors, participants, procesos, services, students, users
sonar.tests=api, certificados, core, deliveries, emails, events, instructors, participants, procesos, services, students, users
sonar.test.inclusions=**/tests.py,**/test_*.py
sonar.exclusions=**/migrations/**,**/admin.py,**/apps.py,config/wsgi.py,config/asgi.py,manage.py,**/management/commands/**,services/whatsapp_service.py,test_student_api.py,certificados/views.py,core/views.py,deliveries/views.py,emails/views.py,events/views.py,instructors/views.py,procesos/views.py,students/views.py,users/views.py,participants/views.py
sonar.exclusions=**/migrations/**,**/admin.py,**/apps.py,config/wsgi.py,config/asgi.py,manage.py,**/management/commands/**,services/whatsapp_service.py,test_student_api.py,certificados/views.py,core/views.py,deliveries/views.py,emails/views.py,events/views.py,instructors/views.py,procesos/views.py,students/views.py,users/views.py,participants/views.py,**/models.py (if only fields),config/celery.py
sonar.python.coverage.reportPaths=coverage.xml