sonar.organization=hectorpq11
sonar.projectKey=hectorpq_certybackend
sonar.projectName=CertyPro - Backend
sonar.language=py
sonar.python.version=3.11

# 🛠️ CORREGIDO: Se eliminaron 'emails' y 'students' de las fuentes
sonar.sources=api, certificados, config, core, deliveries, events, instructors, participants, procesos, services, users

# 🛠️ CORREGIDO: Se eliminaron 'emails' y 'students' de los bloques de pruebas
sonar.tests=api, certificados, core, deliveries, events, instructors, participants, procesos, services, users

sonar.test.inclusions=**/tests.py,**/test_*.py
sonar.exclusions=**/migrations/**,**/admin.py,**/apps.py,config/wsgi.py,config/asgi.py,manage.py,**/management/commands/**,services/whatsapp_service.py,test_student_api.py,certificados/views.py,core/views.py,deliveries/views.py,emails/views.py,events/views.py,instructors/views.py,procesos/views.py,students/views.py,users/views.py,participants/views.py,config/celery.py,config/settings.py
sonar.python.coverage.reportPaths=coverage.xml