# Generated by Django 5.2.12 on 2026-04-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_auditlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="api_auditlo_action_0a1743_idx",
            old_name="api_auditlo_action_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="api_auditlo_timesta_da87a7_idx",
            old_name="api_auditlo_timesta_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="api_auditlo_user_id_b0c441_idx",
            old_name="api_auditlo_user_id_idx",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
