# Generated by Django 5.2.12 on 2026-04-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificados", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="background_image",
            field=models.ImageField(
                blank=True,
                help_text="Imagen de fondo del certificado (PNG/JPG)",
                null=True,
                upload_to="templates/backgrounds/",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="background_url",
            field=models.TextField(
                blank=True, help_text="URL de la imagen de fondo (legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="layout_config",
            field=models.JSONField(
                default=dict,
                help_text='Configuración de posiciones y estilos. Ejemplo:\n        {\n            "student_name": {"x": 100, "y": 150, "font_size": 24, "font_family": "Arial", "color": "#000000"},\n            "event_name": {"x": 100, "y": 200, "font_size": 20, "font_family": "Arial", "color": "#333333"},\n            "event_date": {"x": 100, "y": 250, "font_size": 16, "font_family": "Arial", "color": "#666666"},\n            "verification_code": {"x": 100, "y": 300, "font_size": 14, "font_family": "Arial", "color": "#999999"}\n        }',
            ),
        ),
    ]
