# Generated by Django 5.2.12 on 2026-04-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificados", "0004_add_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="font_color",
            field=models.CharField(default="#000000", max_length=20),
        ),
        migrations.AddField(
            model_name="template",
            name="font_family",
            field=models.CharField(default="Helvetica", max_length=50),
        ),
        migrations.AddField(
            model_name="template",
            name="font_size",
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name="template",
            name="x_coord",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="template",
            name="y_coord",
            field=models.IntegerField(default=150),
        ),
    ]
