# Generated by Django 5.2.12 on 2026-06-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificados", "0004_historicalcertificate_historicaltemplate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltemplate",
            name="layout_config",
            field=models.JSONField(
                default=dict,
                help_text='Configuración de posiciones y estilos. Ejemplo:\n        {\n            "participant_name": {"x": 100, "y": 150, "font_size": 24, "font_family": "Arial", "color": "#000000"},\n            "event_name": {"x": 100, "y": 200, "font_size": 20, "font_family": "Arial", "color": "#333333"},\n            "event_date": {"x": 100, "y": 250, "font_size": 16, "font_family": "Arial", "color": "#666666"},\n            "verification_code": {"x": 100, "y": 300, "font_size": 14, "font_family": "Arial", "color": "#999999"}\n        }',
            ),
        ),
        migrations.AlterField(
            model_name="historicaltemplate",
            name="x_coord",
            field=models.FloatField(default=1.39),
        ),
        migrations.AlterField(
            model_name="historicaltemplate",
            name="y_coord",
            field=models.FloatField(default=2.08),
        ),
        migrations.AlterField(
            model_name="template",
            name="layout_config",
            field=models.JSONField(
                default=dict,
                help_text='Configuración de posiciones y estilos. Ejemplo:\n        {\n            "participant_name": {"x": 100, "y": 150, "font_size": 24, "font_family": "Arial", "color": "#000000"},\n            "event_name": {"x": 100, "y": 200, "font_size": 20, "font_family": "Arial", "color": "#333333"},\n            "event_date": {"x": 100, "y": 250, "font_size": 16, "font_family": "Arial", "color": "#666666"},\n            "verification_code": {"x": 100, "y": 300, "font_size": 14, "font_family": "Arial", "color": "#999999"}\n        }',
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="x_coord",
            field=models.FloatField(default=1.39),
        ),
        migrations.AlterField(
            model_name="template",
            name="y_coord",
            field=models.FloatField(default=2.08),
        ),
    ]
