# Generated by Django 5.2.12 on 2026-04-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificados", "0005_add_x_y_coords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="x_coord",
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name="template",
            name="y_coord",
            field=models.FloatField(default=150.0),
        ),
    ]
