# Generated by Django 5.2.12 on 2026-04-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="participant",
            new_name="participant_is_acti_525b89_idx",
            old_name="participant_is_acti_idx",
        ),
        migrations.RenameIndex(
            model_name="participant",
            new_name="participant_documen_64580f_idx",
            old_name="participant_doc_id_idx",
        ),
        migrations.RenameIndex(
            model_name="participant",
            new_name="participant_email_3b27de_idx",
            old_name="participant_email_idx",
        ),
    ]
