# Generated by Django 5.2.12 on 2026-03-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
