"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
    cast=lambda v: [s.strip() for s in v.split(",")],
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "django_filters",
    "drf_spectacular",
    "simple_history",
    "django_celery_results",
    "certificados",
    "users",
    "participants",
    "instructors",
    "events",
    "core",
    "api",
    "deliveries",
    "procesos",
]
AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ========== EMAIL CONFIGURATION (SMTP) ==========
EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST", default="smtp-relay.brevo.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=15, cast=int)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="Sistema de Certificados <noreply@certypro.app>")
FRONTEND_URL = config("FRONTEND_URL", default="https://certyfront.vercel.app")

# ========== META WHATSAPP CLOUD API ==========
META_WHATSAPP_TOKEN = config("META_WHATSAPP_TOKEN", default="")
META_WHATSAPP_PHONE_ID = config("META_WHATSAPP_PHONE_ID", default="")

# ========== PDF GENERATION PATH ==========
CERTIFICATES_PDF_PATH = BASE_DIR / "certificates" / "pdfs"
CERTIFICATES_PDF_PATH.mkdir(parents=True, exist_ok=True)

# Base URL used inside QR codes for certificate verification
# Override in production with the public-facing domain (e.g. https://certypro.com)
CERTIFICATE_VERIFY_BASE_URL = config("CERTIFICATE_VERIFY_BASE_URL", default="http://localhost:8000")

# ========== CORS CONFIGURATION ==========
# SECURITY WARNING: Update these URLs in production!
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:3000,http://localhost:5173,https://certyfront.vercel.app",
    cast=lambda v: [s.strip() for s in v.split(",")],
)
CORS_ALLOW_CREDENTIALS = True

# ========== REST FRAMEWORK CONFIGURATION ==========
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
}

# ========== DRF SPECTACULAR (OpenAPI/Swagger) ==========
SPECTACULAR_SETTINGS = {
    "TITLE": "SCAD-2026 — Sistema de Certificación Académica Digital",
    "DESCRIPTION": (
        "API REST para gestión de certificados académicos digitales. "
        "Permite la generación, entrega y verificación de certificados "
        "para eventos académicos.\n\n"
        "---\n\n"
        "### Roles del sistema\n\n"
        "- **admin**: Acceso total a todos los recursos del sistema.\n"
        "- **coordinador**: Usuario operativo — gestiona certificados, eventos, participantes e instructores.\n"
        "- **participante**: Usuario final — ve solo sus propios certificados y eventos.\n\n"
        "### Autenticación\n\n"
        "La mayoría de endpoints requieren autenticación via **JWT Bearer Token**.\n"
        "1. Obtén un token usando `POST /api/login/` con email y contraseña.\n"
        "2. Incluye el token en el header `Authorization: Bearer <token>` en cada petición.\n"
        "3. Cuando el token expire, usa `POST /api/token/refresh/` para renovarlo.\n\n"
        "### Paginación\n\n"
        "Las listas están paginadas con 20 ítems por página. "
        "Usa el parámetro `?page=` para navegar entre páginas."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "CONTACT": {"email": "pacompiahectorrobert@gmail.com"},
    "LICENSE": {"name": "Propietaria", "url": "https://certypro.app/license"},
    "SERVERS": [
        {"url": "http://localhost:8000", "description": "Desarrollo local"},
        {"url": "https://api.certypro.app", "description": "Producción"},
    ],
    "COMPONENT_SPLIT_REQUEST": True,
    "SORT_OPERATIONS": True,
    "COMPONENT_SECURITY_SCHEMES": [
        {
            "name": "BearerAuth",
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
            "description": "Ingresa tu token JWT en el formato: `Bearer <token>`. Obténlo en `POST /api/login/`.",
        }
    ],
    "SECURITY": [{"BearerAuth": []}],
    "TAGS": [
        {"name": "Autenticación", "description": "Registro, inicio de sesión, Google OAuth y renovación de tokens."},
        {
            "name": "Certificados",
            "description": "CRUD de certificados, generación de PDF, entrega, "
            "verificación pública, exportación y reintentos.",
        },
        {
            "name": "Certificados - Masivo",
            "description": "Generación masiva de certificados desde archivos Excel "
            "con previsualización y procesamiento.",
        },
        {
            "name": "Eventos",
            "description": "CRUD de eventos académicos, inscripción de participantes, "
            "generación/envío de certificados, invitaciones y estadísticas.",
        },
        {
            "name": "Participantes",
            "description": "CRUD de participantes/estudiantes e importación masiva desde Excel/CSV.",
        },
        {"name": "Instructores", "description": "CRUD de instructores que firman los certificados."},
        {
            "name": "Plantillas",
            "description": "CRUD de plantillas PDF para certificados, carga de imagen de fondo y firma.",
        },
        {
            "name": "Inscripciones",
            "description": "Inscripción de participantes a eventos, marcado de asistencia y notas.",
        },
        {
            "name": "Invitaciones",
            "description": "Invitaciones públicas con token para que participantes se registren y acepten eventos.",
        },
        {"name": "Registros de Entrega", "description": "Historial de todos los intentos de entrega de certificados."},
        {"name": "Auditoría", "description": "Log completo de acciones del sistema (solo administradores)."},
    ],
}

# ========== JWT CONFIGURATION ==========
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
}

# ========== GOOGLE OAUTH CONFIGURATION ==========
GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID", default="")

# ========== MEDIA FILES ==========
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ========== SECURITY SETTINGS (Production) ==========
# These settings should be configured in production environment
# See: https://docs.djangoproject.com/en/5.2/topics/security/

# CSRF Settings
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="http://localhost:5173,http://localhost:8000",
    cast=lambda v: [s.strip() for s in v.split(",")],
)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=False, cast=bool)  # True in production with HTTPS
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Lax"

# Session Settings
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=False, cast=bool)  # True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 1209600  # 2 weeks

# Security Middleware Settings (enabled via SecurityMiddleware)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# HSTS Settings (enable in production after HTTPS is confirmed working)
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=0, cast=int)  # Set to 31536000 in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = config("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False, cast=bool)
SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=False, cast=bool)

# SSL Redirect (enable in production)
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=False, cast=bool)

# Referrer Policy
REFERRER_POLICY = "strict-origin-when-cross-origin"

# ========== CSRF CONFIGURATION ==========
# CSRF settings are configured above with other security settings

# ========== CELERY CONFIGURATION ==========
CELERY_BROKER_URL = config("REDIS_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "default"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 240  # 4 minutes soft limit
