# Generated by Django 5.2.12 on 2026-03-29 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('link', 'Link')], max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='certificados.certificate')),
            ],
            options={
                'verbose_name': 'Delivery Log',
                'verbose_name_plural': 'Delivery Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
