# Generated by Django 5.2.12 on 2026-03-29 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['status'], name='deliveries__status_d84956_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['delivery_method'], name='deliveries__deliver_961d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['certificate'], name='deliveries__certifi_f3909a_idx'),
        ),
    ]
