# Generated by Django 5.2.12 on 2026-04-28 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="deliverylog",
            new_name="deliveries__status_d84956_idx",
            old_name="delivery_status_idx",
        ),
        migrations.RenameIndex(
            model_name="deliverylog",
            new_name="deliveries__deliver_961d2a_idx",
            old_name="delivery_method_idx",
        ),
        migrations.RenameIndex(
            model_name="deliverylog",
            new_name="deliveries__certifi_f3909a_idx",
            old_name="delivery_cert_idx",
        ),
        migrations.AlterField(
            model_name="deliverylog",
            name="sent_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
