# Generated by Django 5.2.12 on 2026-03-29 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_alter_deliverylog_options_deliverylog_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverylog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Delivery Log', 'verbose_name_plural': 'Delivery Logs'},
        ),
    ]
